Run_File : add.c  create.c delete.c display.c login.c Project_client.c totalStudents.c update.c error_check.c Server.h internal_header.h sqlite3.h
	gcc add.c create.c delete.c display.c login.c Project_client.c totalStudents.c update.c error_check.c -o Run_File -l sqlite3 Server.h internal_header.h
